server:
  port: 9090
springdoc:
  swagger-ui:
    tagsSorter: alpha
    operationsSorter: method
spring:
  security:
    user:
      password: "123"
      name: "user"
config:
  aws:
    access-key: "AKIASFHGCAHG3XLLIAND"
    secret-key: "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"
    region: "us-east-1"
