server:
  port: 9090
springdoc:
  swagger-ui:
    tagsSorter: alpha
    operationsSorter: method
spring:
  security:
    user:
      password: "123"
      name: "user"
config:
  aws:
    access-key: "AKIASFHGCAHGXAADMB6Y"
    secret-key: "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"
    region: "us-east-1"
