server:
  port: 9090
springdoc:
  swagger-ui:
    tagsSorter: alpha
    operationsSorter: method
security:
  enable:
    csrf: false
spring:
  security:
    user:
      password: "123"
      name: "user"
